In [95]:
import os, glob
import nibabel as nib
import torchio as tio
import numpy as np
from PIL import Image
from skimage.transform import resize, rescale

In [96]:
label_path = '7_spacing.nii.gz'

In [ ]:
#############################################

In [ ]:
label = tio.LabelMap(label_path)
print(label.shape)
print(np.unique(label, return_counts=True))

In [ ]:
transform_resize = tio.Resize(target_shape=(128,128,512))

In [ ]:
output = transform_resize(subject)
print(output.shape)
print(np.unique(output, return_counts=True))

In [ ]:
output.save('7_resize_tio.nii.gz')

In [ ]:
#############################################

In [87]:
def read_nifti_file(filepath):
    """Read and load volume"""
    # Read file
    scan = nib.load(filepath)
    # Get raw data
    scan = scan.get_fdata()
    return scan

In [88]:
label = read_nifti_file(label_path)
print(label.shape)
print(np.unique(label, return_counts=True))

(553, 553, 482)
(array([0., 1., 2.]), array([147376847,     15948,      7143]))


In [89]:
result = resize(label, (128,128,512), order=0, preserve_range=True, anti_aliasing=False)
print(result.shape)
print(np.unique(result, return_counts=True))

(256, 256, 512)
(array([0., 1., 2.]), array([33549155,     3711,     1566]))


In [90]:
result = nib.Nifti1Image(result, np.eye(4))
nib.save(result, '7_resize_skimage.nii.gz')

In [91]:
# Interpolate to 512x512x512
label_resized = read_nifti_file('7_skimage_resize.nii.gz')
print(label_resized.shape)

(256, 256, 512)


In [93]:
interpolated = resize(label_resized, (512,512,512), order=0, preserve_range=True, anti_aliasing=False)
print(interpolated.shape)
print(np.unique(interpolated, return_counts=True))

(512, 512, 512)
(array([0., 1., 2.]), array([134196620,     14844,      6264]))


In [94]:
interpolated = nib.Nifti1Image(interpolated, np.eye(4))
nib.save(interpolated, '7_skimage_interpolated.nii.gz')