In [113]:
import os, glob
import nibabel as nib
import skimage.transform as sktrans
import numpy as np

In [104]:
label_path = '7_spacing.nii.gz'

In [114]:
def read_nifti_file(filepath):
    """Read and load volume"""
    # Read file
    scan = nib.load(filepath)
    # Get raw data
    scan = scan.get_fdata()
    return scan

In [106]:
label = read_nifti_file(label_path)
print(label.shape)
print(np.unique(label, return_counts=True))

(553, 553, 482)
(array([0., 1., 2.]), array([147376847,     15948,      7143]))


In [107]:
# Resize to 128x128x512
result = sktrans.resize(label, (128,128,512), order=0, preserve_range=True, anti_aliasing=False)
print(result.shape)
print(np.unique(result, return_counts=True))

(128, 128, 512)
(array([0., 1., 2.]), array([8387247,     929,     432]))


In [108]:
result = nib.Nifti1Image(result, np.eye(4))
nib.save(result, '7_skimage_resize.nii.gz')

In [100]:
# Interpolate to 512x512x512
label_resized = read_nifti_file('7_skimage_resize.nii.gz')
print(label_resized.shape)

(128, 128, 512)


In [101]:
interpolated = sktrans.resize(label_resized, (512,512,512), order=0, preserve_range=True, anti_aliasing=False)
print(interpolated.shape)
print(np.unique(interpolated, return_counts=True))

(512, 512, 512)
(array([0.00000000e+00, 1.09740712e-09, 2.19481423e-09, ...,
       1.73344286e+00, 1.76889815e+00, 1.78439543e+00]), array([133963472,      3936,      1424, ...,        16,        16,
              16]))


In [102]:
interpolated = nib.Nifti1Image(interpolated, np.eye(4))
nib.save(interpolated, '7_skimage_interpolated.nii.gz')