Some files have `facial` as `1` and `temporal` as `2`. This notebook will correct those labels i.e. `temporal` to `1` and `facial` to `2`.

In [18]:
import nibabel as nib
import numpy as np
import glob, os

In [19]:
def read_nifti_file(filepath):
    """Read and load volume"""
    # Read file
    scan = nib.load(filepath)
    # Get raw data
    scan = scan.get_fdata()
    return scan

In [20]:
path = '/media/trojan/evo/3D-CT-Artery-Segmentation/data/data_new/data_original/temp/masks'

In [8]:
for mask in glob.glob(path + '/*.nii.gz'):
    label = read_nifti_file(mask)
    print(np.unique(label, return_counts=True))

(array([0., 1., 2.]), array([38787087,     3519,     6706]))
(array([0., 1., 2.]), array([26992928,     3314,     4590]))
(array([0., 1., 2.]), array([35626898,     3523,    21163]))
(array([0., 1., 2.]), array([19919728,     1123,     2093]))
(array([0., 1., 2.]), array([160930364,     11074,     14978]))
(array([0., 1., 2.]), array([32223279,     5334,    15099]))
(array([0., 1., 2.]), array([49790485,     6682,    10193]))
(array([0., 1., 2.]), array([21754055,     1312,     2585]))
(array([0., 1., 2.]), array([30141395,     1755,     3410]))
(array([0., 1., 2.]), array([132102646,      8279,      9651]))
(array([0., 1., 2.]), array([47954119,     6057,    12176]))
(array([0., 1., 2.]), array([47950632,     5093,    16627]))
(array([0., 1., 2.]), array([61323288,     4047,    14361]))
(array([0., 1., 2.]), array([34061295,     5287,    12138]))
(array([0., 1., 2.]), array([20181520,     1530,     2038]))
(array([0., 1., 2.]), array([25423241,     2132,     2595]))
(array([0., 1., 2.

`Temporal` has more number of points than `facial` always. But here that is not the case which means labels are reversed.

In [21]:
out_path = '/media/trojan/evo/3D-CT-Artery-Segmentation/data/data_new/data_original/temp/fixed_masks'

In [25]:
# Fix the labels
for mask in glob.glob(path + '/*.nii.gz'):
    name = mask.split('/')[-1]
    label = read_nifti_file(mask)
    label[label==2] = 999  # placeholder value
    label[label==1] = 2
    label[label==999] = 1
    label_arr = nib.Nifti1Image(label, None)
    nib.save(label_arr, os.path.join(out_path, name))

In [26]:
for mask in glob.glob(out_path + '/*.nii.gz'):
    label = read_nifti_file(mask)
    print(np.unique(label, return_counts=True))

(array([0., 1., 2.]), array([38787087,     6706,     3519]))
(array([0., 1., 2.]), array([26992928,     4590,     3314]))
(array([0., 1., 2.]), array([35626898,    21163,     3523]))
(array([0., 1., 2.]), array([19919728,     2093,     1123]))
(array([0., 1., 2.]), array([160930364,     14978,     11074]))
(array([0., 1., 2.]), array([32223279,    15099,     5334]))
(array([0., 1., 2.]), array([49790485,    10193,     6682]))
(array([0., 1., 2.]), array([21754055,     2585,     1312]))
(array([0., 1., 2.]), array([30141395,     3410,     1755]))
(array([0., 1., 2.]), array([132102646,      9651,      8279]))
(array([0., 1., 2.]), array([47954119,    12176,     6057]))
(array([0., 1., 2.]), array([47950632,    16627,     5093]))
(array([0., 1., 2.]), array([61323288,    14361,     4047]))
(array([0., 1., 2.]), array([34061295,    12138,     5287]))
(array([0., 1., 2.]), array([20181520,     2038,     1530]))
(array([0., 1., 2.]), array([25423241,     2595,     2132]))
(array([0., 1., 2.